# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish minor

on:
  push:
    branches:
      - minor

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: npm install
      run: npm ci
    - name: version
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm version minor -m "Version %s"
        git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git push gh-origin HEAD:minor --tags
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Rebase master on patch
      # Recommended: specify a version such as `@v1.0` rather than `@main`
      uses: DeeDeeG/rebase-github-action@main
      with:
        # Head branch, which will be rebased onto the base_ref.
        head_branch: master
        # Branch, or Git ref, that the head_branch will be rebased onto.
        base_ref: origin/minor